"""initial create

Revision ID: 540b04e0762c
Revises: 
Create Date: 2024-05-07 18:41:26.360913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540b04e0762c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yt__credentials')
    op.drop_table('_alembic_tmp_upload')
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_upload',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('yt_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('channel_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('dateTime', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yt_id')
    )
    op.create_table('yt__credentials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('credentials', sa.VARCHAR(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
