"""'Upload': add 'is_short' column 

Revision ID: 7317681455ef
Revises: 540b04e0762c
Create Date: 2024-05-22 00:37:29.239785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7317681455ef'
down_revision = '540b04e0762c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_short', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('is_short')

    # ### end Alembic commands ###
