"""create yt_credentials table

Revision ID: dddd8d4df501
Revises: 9f4cc9fa6c35
Create Date: 2024-06-02 16:40:42.539991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddd8d4df501'
down_revision = '9f4cc9fa6c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yt_credentials',
    sa.Column('yt_id', sa.String(length=100), nullable=False),
    sa.Column('yt_name', sa.String(length=100), nullable=False),
    sa.Column('_oauth_token', sa.String(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('yt_id'),
    sa.UniqueConstraint('_oauth_token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yt_credentials')
    # ### end Alembic commands ###
