"""add strict shorts detection setting

Revision ID: 220983e5f725
Revises: a78fc80ed28e
Create Date: 2026-09-03 23:29:25.530319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220983e5f725'
down_revision: Union[str, None] = 'a78fc80ed28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills the existing settings row with the ORM
    # model's default (off), then is dropped so it doesn't linger as a
    # DB-level default going forward.
    op.add_column(
        'app_settings',
        sa.Column('strict_shorts_detection', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.alter_column('strict_shorts_detection', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'strict_shorts_detection')
    # ### end Alembic commands ###
