"""add channel sync jobs table

Revision ID: 81036ef4ec69
Revises: 916d552dac8e
Create Date: 2026-09-04 01:23:17.375865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81036ef4ec69'
down_revision: Union[str, None] = '916d552dac8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('new_uploads_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', name='uq_channel_sync_job_channel')
    )
    op.create_index(op.f('ix_channel_sync_jobs_channel_id'), 'channel_sync_jobs', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_sync_jobs_channel_id'), table_name='channel_sync_jobs')
    op.drop_table('channel_sync_jobs')
    # ### end Alembic commands ###
