"""add sync and backfill worker intervals to settings

Revision ID: 89dab9af7498
Revises: a3dee3c2d247
Create Date: 2026-09-03 22:13:05.454246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89dab9af7498'
down_revision: Union[str, None] = 'a3dee3c2d247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills the existing settings row (there's exactly
    # one) with the same defaults the ORM model uses for new rows; dropped
    # afterward so it doesn't linger as a DB-level default going forward.
    op.add_column(
        'app_settings',
        sa.Column('sync_interval_minutes', sa.Integer(), nullable=False, server_default='30'),
    )
    op.add_column(
        'app_settings',
        sa.Column('backfill_worker_interval_seconds', sa.Integer(), nullable=False, server_default='60'),
    )
    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.alter_column('sync_interval_minutes', server_default=None)
        batch_op.alter_column('backfill_worker_interval_seconds', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'backfill_worker_interval_seconds')
    op.drop_column('app_settings', 'sync_interval_minutes')
    # ### end Alembic commands ###
