"""add sync log subscription progress tracking

Revision ID: 9016370664e3
Revises: 9473c174a8b1
Create Date: 2026-09-04 12:50:59.638005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9016370664e3'
down_revision: Union[str, None] = '9473c174a8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_logs', sa.Column('total_subscriptions', sa.Integer(), nullable=True))
    op.add_column(
        'sync_logs',
        sa.Column('subscriptions_processed', sa.Integer(), nullable=False, server_default='0'),
    )
    with op.batch_alter_table('sync_logs') as batch_op:
        batch_op.alter_column('subscriptions_processed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_logs', 'subscriptions_processed')
    op.drop_column('sync_logs', 'total_subscriptions')
    # ### end Alembic commands ###
