"""add video type verified flag

Revision ID: 916d552dac8e
Revises: 220983e5f725
Create Date: 2026-09-03 23:49:25.349032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916d552dac8e'
down_revision: Union[str, None] = '220983e5f725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows with the ORM model's default
    # (unverified), then is dropped so it doesn't linger as a DB-level
    # default going forward.
    op.add_column(
        'uploads',
        sa.Column('video_type_verified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    with op.batch_alter_table('uploads') as batch_op:
        batch_op.alter_column('video_type_verified', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'video_type_verified')
    # ### end Alembic commands ###
