"""remove api key groups and fetch method, add update tasks and rss fallback settings

Revision ID: 9473c174a8b1
Revises: 81036ef4ec69
Create Date: 2026-09-04 02:27:11.975944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9473c174a8b1'
down_revision: Union[str, None] = '81036ef4ec69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('resume_cursor', sa.String(length=255), nullable=True),
    sa.Column('oldest_fetched_published_at', sa.DateTime(), nullable=True),
    sa.Column('used_rss_fallback', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_update_tasks_channel_id'), 'update_tasks', ['channel_id'], unique=False)
    op.create_index(op.f('ix_update_tasks_status'), 'update_tasks', ['status'], unique=False)
    op.drop_index(op.f('ix_channel_sync_jobs_channel_id'), table_name='channel_sync_jobs')
    op.drop_table('channel_sync_jobs')
    op.drop_column('api_keys', 'group')
    op.add_column(
        'app_settings',
        sa.Column('update_lookback_days', sa.Integer(), nullable=False, server_default='30'),
    )
    op.add_column(
        'app_settings',
        sa.Column('rss_fallback_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    with op.batch_alter_table('app_settings') as batch_op:
        batch_op.alter_column('update_lookback_days', server_default=None)
        batch_op.alter_column('rss_fallback_enabled', server_default=None)
    op.drop_column('app_settings', 'upload_fetch_method')
    op.drop_column('channels', 'upload_fetch_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('upload_fetch_method', sa.VARCHAR(length=8), nullable=True))
    op.add_column('app_settings', sa.Column('upload_fetch_method', sa.VARCHAR(length=8), nullable=False))
    op.drop_column('app_settings', 'rss_fallback_enabled')
    op.drop_column('app_settings', 'update_lookback_days')
    op.add_column('api_keys', sa.Column('group', sa.VARCHAR(length=16), nullable=False))
    op.create_table('channel_sync_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('channel_id', sa.INTEGER(), nullable=False),
    sa.Column('method', sa.VARCHAR(length=8), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('new_uploads_count', sa.INTEGER(), nullable=False),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', name=op.f('uq_channel_sync_job_channel'))
    )
    op.create_index(op.f('ix_channel_sync_jobs_channel_id'), 'channel_sync_jobs', ['channel_id'], unique=False)
    op.drop_index(op.f('ix_update_tasks_status'), table_name='update_tasks')
    op.drop_index(op.f('ix_update_tasks_channel_id'), table_name='update_tasks')
    op.drop_table('update_tasks')
    # ### end Alembic commands ###
