"""initial schema

Revision ID: a3dee3c2d247
Revises: 
Create Date: 2026-09-03 01:23:23.412302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dee3c2d247'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('key_value_encrypted', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quota_resets_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('upload_fetch_method', sa.String(length=8), nullable=False),
    sa.Column('backfill_days', sa.Integer(), nullable=False),
    sa.Column('backfill_min_count', sa.Integer(), nullable=False),
    sa.Column('youtube_refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=True),
    sa.Column('youtube_channel_title', sa.String(length=255), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('subscription_status', sa.String(length=16), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.Column('unsubscribed_ack', sa.Boolean(), nullable=False),
    sa.Column('upload_fetch_method', sa.String(length=8), nullable=True),
    sa.Column('backfill_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_youtube_channel_id'), 'channels', ['youtube_channel_id'], unique=True)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channels_added', sa.Integer(), nullable=False),
    sa.Column('channels_marked_unsubscribed', sa.Integer(), nullable=False),
    sa.Column('rss_fallback_channels', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('backfill_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_min_count', sa.Integer(), nullable=False),
    sa.Column('target_after', sa.Date(), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('resume_cursor', sa.String(length=255), nullable=True),
    sa.Column('oldest_fetched_published_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backfill_tasks_channel_id'), 'backfill_tasks', ['channel_id'], unique=False)
    op.create_index(op.f('ix_backfill_tasks_status'), 'backfill_tasks', ['status'], unique=False)
    op.create_table('channel_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'tag_id', name='uq_channel_tag')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('fetched_via', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'youtube_video_id', name='uq_channel_video')
    )
    op.create_index(op.f('ix_uploads_channel_id'), 'uploads', ['channel_id'], unique=False)
    op.create_index(op.f('ix_uploads_published_at'), 'uploads', ['published_at'], unique=False)
    op.create_index(op.f('ix_uploads_youtube_video_id'), 'uploads', ['youtube_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_youtube_video_id'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_published_at'), table_name='uploads')
    op.drop_index(op.f('ix_uploads_channel_id'), table_name='uploads')
    op.drop_table('uploads')
    op.drop_table('channel_tags')
    op.drop_index(op.f('ix_backfill_tasks_status'), table_name='backfill_tasks')
    op.drop_index(op.f('ix_backfill_tasks_channel_id'), table_name='backfill_tasks')
    op.drop_table('backfill_tasks')
    op.drop_table('tags')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_channels_youtube_channel_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_table('app_settings')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
