"""add channel subscribed_at and upload video_type

Revision ID: a78fc80ed28e
Revises: 89dab9af7498
Create Date: 2026-09-03 22:43:46.897369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78fc80ed28e'
down_revision: Union[str, None] = '89dab9af7498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('channels', sa.Column('subscribed_at', sa.DateTime(), nullable=True))
    # server_default backfills existing rows with the ORM model's default
    # ("video"), then is dropped so it doesn't linger as a DB-level default.
    op.add_column(
        'uploads',
        sa.Column('video_type', sa.String(length=8), nullable=False, server_default='video'),
    )
    with op.batch_alter_table('uploads') as batch_op:
        batch_op.alter_column('video_type', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'video_type')
    op.drop_column('channels', 'subscribed_at')
    # ### end Alembic commands ###
